# Generated by Django 5.1.4 on 2025-01-10 08:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_creditscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditscore',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
